// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_middleware from "./routes/(platform)/_middleware.ts";
import * as $_platform_character_id_ from "./routes/(platform)/character/[id].tsx";
import * as $_platform_characters from "./routes/(platform)/characters.tsx";
import * as $_platform_favorites from "./routes/(platform)/favorites.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_nuevofavorito from "./routes/api/nuevofavorito.ts";
import * as $api_quitarfavoritos from "./routes/api/quitarfavoritos.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $IslaCharacter from "./islands/IslaCharacter.tsx";
import * as $IslaFavoritesCharacters from "./islands/IslaFavoritesCharacters.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/_middleware.ts": $_platform_middleware,
    "./routes/(platform)/character/[id].tsx": $_platform_character_id_,
    "./routes/(platform)/characters.tsx": $_platform_characters,
    "./routes/(platform)/favorites.tsx": $_platform_favorites,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/nuevofavorito.ts": $api_nuevofavorito,
    "./routes/api/quitarfavoritos.ts": $api_quitarfavoritos,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/IslaCharacter.tsx": $IslaCharacter,
    "./islands/IslaFavoritesCharacters.tsx": $IslaFavoritesCharacters,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
